### ISSUE TITLE
img

### ISSUE THREAD

**Issue by stormtea123** [stormtea123/panda#3]
![1](https://cloud.githubusercontent.com/assets/1193966/15237919/3edb25c4-1905-11e6-9a9a-be8851951840.png)
![2](https://cloud.githubusercontent.com/assets/1193966/15237920/3edb94a0-1905-11e6-992e-84fa3a7b91c4.gif)
![3](https://cloud.githubusercontent.com/assets/1193966/15237923/3edf94ec-1905-11e6-91ac-e600ee16a771.gif)
![4](https://cloud.githubusercontent.com/assets/1193966/15237921/3edf1ff8-1905-11e6-9734-b6b060e3a9ae.png)
![logo](https://cloud.githubusercontent.com/assets/1193966/15237922/3edf64c2-1905-11e6-9503-b5cd0765313f.png)

**Comment by leibnizli** [comment]
![panda](https://github.com/leibnizli/panda/assets/1193966/5abe092c-8cb1-4dc7-af4d-14beff7a9676)
